### ISSUE TITLE
Pre audit checklist

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/dough-staking#9]
- [x] Remove console.logs
- [x] Events (eject, redistribute, etc)
- [x] Remove unused testing contracts
- [x] Run coverage
- [x] Deployment scripts
- [x] Possible gas savings
